CREATE TABLE IF NOT EXISTS USER_INFO(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(222) NOT NULL,
    EMAIL VARCHAR(53) NOT NULL,
    PASSWORD VARCHAR(53) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_BOOKING(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(222) NOT NULL,
    EMAIL VARCHAR(53) NOT NULL,
    BUILDING_ VARCHAR(33) NOT NULL,
    DAY_ VARCHAR(20) NOT NULL,
    TIME_ VARCHAR(20) NOT NULL,
    ROOM_ INT NOT NULL,
);

CREATE TABLE IF NOT EXISTS LAB(
    NO_ INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BUILDING_ VARCHAR(33) NOT NULL,
    DAY_ VARCHAR(20) NOT NULL,
    TIME_ VARCHAR(20) NOT NULL,
    ROOM_ INT NOT NULL,
    GROUP_ VARCHAR(33) NOT NULL,
    AVAILABLE_ VARCHAR(33) NOT NULL
);

CREATE TABLE IF NOT EXISTS STUDY_ROOM(
    NO_ INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BUILDING_ VARCHAR(33) NOT NULL,
    DAY_ VARCHAR(20) NOT NULL,
    TIME_ VARCHAR(20) NOT NULL,
    ROOM_ INT NOT NULL,
    GROUP_ VARCHAR(33) NOT NULL,
    AVAILABLE_ VARCHAR(33) NOT NULL
);



SELECT * FROM STUDY_ROOM;

SELECT * FROM USER_INFO;

SELECT * from LAB;

SELECT * from USER_BOOKING;


DROP TABLE IF EXISTS STUDY_ROOM;

DROP TABLE IF EXISTS LAB;

DROP TABLE IF EXISTS USER_INFO;
